### ISSUE TITLE
error when installing

### ISSUE THREAD

**Issue by adrian-rt** [airbus-seclab/bincat#125]
C:\Users\adria\Downloads\bincat-win-v1.1\install_plugin.py: 'module' object has no attribute 'main'
Traceback (most recent call last):
  File "C:\Program Files\IDA 7.2\python\ida_idaapi.py", line 572, in IDAPython_ExecScript
    execfile(script, g)
  File "C:/Users/adria/Downloads/bincat-win-v1.1/install_plugin.py", line 25, in <module>
    pip.main(['install', "requests"])
AttributeError: 'module' object has no attribute 'main'

**Comment by trou** [comment]
Which python version are you using ?

**Comment by adrian-rt** [comment]
2.7

**Comment by trou** [comment]
This was due to an internal change in `pip`'s module. This has been fixed in 6768f89731c84a52e947f4996e3933cdf323ccb1 by removing the auto install functionality.
