### ISSUE TITLE
Crash with Python 3.10 in IDA 7.6 Linux

### ISSUE THREAD

**Issue by trou** [airbus-seclab/bincat#127]
```
gef➤  py-bt
Traceback (most recent call first):
  <built-in function connectSlotsByName>
  File "/home/raph/.idapro/plugins/idabincat/hexview/hexview_auto.py", line 27, in setupUi
    QtCore.QMetaObject.connectSlotsByName(Form)
  File "/home/raph/.idapro/plugins/idabincat/hexview/hexview.py", line 612, in __init__
    self.setupUi(self)
  File "/home/raph/.idapro/plugins/idabincat/gui.py", line 427, in OnCreate
    self.hexwidget = hexview.HexViewWidget(
  <built-in method plgform_show of module object at remote 0x7ffff048b9b0>
  File "/home/raph/bin/ida76/python/3/ida_kernwin.py", line 11805, in Show
    return _ida_kernwin.plgform_show(self.__clink__, self, caption, options)
  File "/home/raph/.idapro/plugins/idabincat/gui.py", line 494, in Show
    return ida_kernwin.PluginForm.Show(
  File "/home/raph/.idapro/plugins/idabincat/gui.py", line 2271, in show_windows
    self.BinCATMemForm.Show()
  File "/home/raph/.idapro/plugins/bcplugin.py", line 172, in run
    self.state.gui.show_windows()
```

```
gef➤  bt
#0  __GI_raise (sig=sig@entry=0x6) at ../sysdeps/unix/sysv/linux/raise.c:49
#1  0x00007ffff5c14536 in __GI_abort () at abort.c:79
#2  0x00007ffff5c1441f in __assert_fail_base (fmt=0x7ffff30c05d9 "%s%s%s :%u : %s%s l'assertion « %s » a échoué.\n%n", assertion=0x7ffff0fa303d "!PyErr_Occurred()", file=0x7ffff0fc16c3 "../Objects/typeobject.c", line=0xee5, function=<optimized out>) at assert.c:92
#3  0x00007ffff5c237f2 in __GI___assert_fail (assertion=assertion@entry=0x7ffff0fa303d "!PyErr_Occurred()", file=file@entry=0x7ffff0fc16c3 "../Objects/typeobject.c", line=line@entry=0xee5, function=function@entry=0x7ffff0fc5288 <__PRETTY_FUNCTION__.87> "_PyType_Lookup") at assert.c:101
#4  0x00007ffff0d75d52 in _PyType_Lookup (type=type@entry=0x5555573237a0, name=name@entry=0x7fffd9de6a40) at ../Objects/typeobject.c:3813
#5  0x00007ffff0d54b2d in _PyObject_GenericGetAttrWithDict (obj=obj@entry=0x7fffd9e20cd0, name=name@entry=0x7fffd9de6a40, dict=dict@entry=0x0, suppress=suppress@entry=0x0) at ../Objects/object.c:1236
#6  0x00007ffff0d551a7 in PyObject_GenericGetAttr (obj=obj@entry=0x7fffd9e20cd0, name=name@entry=0x7fffd9de6a40) at ../Objects/object.c:1322
#7  0x00007ffff0d79e54 in slot_tp_getattr_hook (self=0x7fffd9e20cd0, name=0x7fffd9de6a40) at ../Objects/typeobject.c:7556
#8  0x00007ffff0d54854 in PyObject_GetAttr (v=0x7fffd9e20cd0, name=0x7fffd9de6a40) at ../Objects/object.c:922
#9  0x00007fffdafa3625 in  () at /home/raph/bin/ida76/python/3/PyQt5/QtCore.so
#10 0x00007fffdaef8bc8 in  () at /home/raph/bin/ida76/python/3/PyQt5/QtCore.so
#11 0x00007ffff0d4cd5e in cfunction_call (func=0x7fffd9e35c70, args=<optimized out>, kwargs=<optimized out>) at ../Objects/methodobject.c:552
#12 0x00007ffff0cf82e5 in _PyObject_MakeTpCall (tstate=tstate@entry=0x5555561800c0, callable=callable@entry=0x7fffd9e35c70, args=args@entry=0x7fffd9e383a0, nargs=<optimized out>, keywords=keywords@entry=0x0) at ../Objects/call.c:215
#13 0x00007ffff0e03206 in _PyObject_VectorcallTstate (tstate=0x5555561800c0, callable=0x7fffd9e35c70, args=0x7fffd9e383a0, nargsf=<optimized out>, kwnames=0x0) at ../Include/cpython/abstract.h:112
```

Possibly a bug in PyQt5 ?

**Comment by af-airbus** [comment]
Could you please try the current master version?

**Comment by af-airbus** [comment]
Is this issue still relevant? Could you close the issue accordingly?
