### ISSUE TITLE
v0.7rc fails with IDA 7 32 bits

### ISSUE THREAD

**Issue by trou** [airbus-seclab/bincat#44]
```
Traceback (most recent call last):
  File "/home/raph/.idapro/plugins/bcplugin.py", line 277, in procanalyzer_on_finish
    self.process_output()
  File "/home/raph/.idapro/plugins/bcplugin.py", line 299, in process_output
    self.finish_cb(self.outfname, self.logfname, self.cfaoutfname)
  File "/home/raph/.idapro/plugins/bcplugin.py", line 574, in analysis_finish_cb
    self.netnode["analyzer.log"] = f.read()
  File "/home/raph/.idapro/python/idabincat/netnode.py", line 147, in __setitem__
    d = self._compress(self._encode(value))
  File "/home/raph/.idapro/python/idabincat/netnode.py", line 94, in _encode
    return json.dumps(data)
  File "/home/raph/bin/ida7-32/python/lib/python27.zip/json/__init__.py", line 243, in dumps
  File "/home/raph/bin/ida7-32/python/lib/python27.zip/json/encoder.py", line 201, in encode
SystemError: Objects/stringobject.c:3904: bad argument to internal function
```

**Comment by trou** [comment]
I cannot reproduce ...

**Comment by trou** [comment]
Closing for now, I'll reopen if I can reproduce
