### ISSUE TITLE
Could not work with IDA 7.0

### ISSUE THREAD

**Issue by perfectswpuboy1** [airbus-seclab/bincat#90]
1. When I just load the script to install,It's not work.
![ApcGmPb1KF](https://user-images.githubusercontent.com/356742/54682456-efd63700-4b49-11e9-9f27-394dabae3c26.png)

2.When I install it mannually,It's not work too!

When I just tried by the tutor,It's not gonna to work.
> The initial autoanalysis has been finished.
WARNING:bincat.gui.pluginoptions:IDAUSR not defined, using C:\Users\x230\AppData\Roaming\Hex-Rays\IDA Pro
WARNING:bincat.plugin:Could not find bincat binary, will not be able to run local analysis
WARNING:bincat-cfg:Default config file C:\Users\x230\AppData\Roaming\Hex-Rays\IDA Pro\idabincat\conf\default.ini could not be found
ERROR:bincat-cfg:No code section has been found for entrypoint 0X00093B
Traceback (most recent call last):
  File "C:/Program Files/IDA 7.0/plugins\idabincat\gui.py", line 879, in _load_config
    self.s.current_ea, None, self.get_analysis_method())
  File "C:/Program Files/IDA 7.0/plugins\idabincat\analyzer_conf.py", line 899, in new_config
    analysis_config)
  File "C:/Program Files/IDA 7.0/plugins\idabincat\analyzer_conf.py", line 743, in get_default_config
    config.set('analyzer', 'analysis_ep', "0x%0X" % analysis_start_va)
  File "C:\python27-x64\Lib\ConfigParser.py", line 396, in set
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'analyzer'
INFO:bincat.plugin:IDABinCAT ready.
Traceback (most recent call last):
  File "C:/Program Files/IDA 7.0/plugins\idabincat\gui.py", line 945, in _edit_config
    self._update_edit_config()
  File "C:/Program Files/IDA 7.0/plugins\idabincat\gui.py", line 787, in _update_edit_config
    self.s.edit_config.analysis_ep = start_addr
AttributeError: 'NoneType' object has no attribute 'analysis_ep'
Traceback (most recent call last):
  File "C:/Program Files/IDA 7.0/plugins\idabincat\gui.py", line 945, in _edit_config
    self._update_edit_config()
  File "C:/Program Files/IDA 7.0/plugins\idabincat\gui.py", line 787, in _update_edit_config
    self.s.edit_config.analysis_ep = start_addr
AttributeError: 'NoneType' object has no attribute 'analysis_ep'
Traceback (most recent call last):
  File "C:/Program Files/IDA 7.0/plugins\idabincat\gui.py", line 945, in _edit_config
    self._update_edit_config()
  File "C:/Program Files/IDA 7.0/plugins\idabincat\gui.py", line 787, in _update_edit_config
    self.s.edit_config.analysis_ep = start_addr
AttributeError: 'NoneType' object has no attribute 'analysis_ep'
Traceback (most recent call last):
  File "C:/Program Files/IDA 7.0/plugins\idabincat\gui.py", line 945, in _edit_config
    self._update_edit_config()
  File "C:/Program Files/IDA 7.0/plugins\idabincat\gui.py", line 787, in _update_edit_config
    self.s.edit_config.analysis_ep = start_addr
AttributeError: 'NoneType' object has no attribute 'analysis_ep'
Traceback (most recent call last):
  File "C:/Program Files/IDA 7.0/plugins\idabincat\gui.py", line 945, in _edit_config
    self._update_edit_config()
  File "C:/Program Files/IDA 7.0/plugins\idabincat\gui.py", line 787, in _update_edit_config
    self.s.edit_config.analysis_ep = start_addr
AttributeError: 'NoneType' object has no attribute 'analysis_ep'
Traceback (most recent call last):
  File "C:/Program Files/IDA 7.0/plugins\idabincat\gui.py", line 945, in _edit_config
    self._update_edit_config()
  File "C:/Program Files/IDA 7.0/plugins\idabincat\gui.py", line 787, in _update_edit_config
    self.s.edit_config.analysis_ep = start_addr
AttributeError: 'NoneType' object has no attribute 'analysis_ep'
Traceback (most recent call last):
  File "C:/Program Files/IDA 7.0/plugins\idabincat\gui.py", line 945, in _edit_config
    self._update_edit_config()
  File "C:/Program Files/IDA 7.0/plugins\idabincat\gui.py", line 787, in _update_edit_config
    self.s.edit_config.analysis_ep = start_addr
AttributeError: 'NoneType' object has no attribute 'analysis_ep'
Traceback (most recent call last):
  File "C:/Program Files/IDA 7.0/plugins\idabincat\gui.py", line 945, in _edit_config
    self._update_edit_config()
  File "C:/Program Files/IDA 7.0/plugins\idabincat\gui.py", line 787, in _update_edit_config
    self.s.edit_config.analysis_ep = start_addr
AttributeError: 'NoneType' object has no attribute 'analysis_ep'

**Comment by perfectswpuboy1** [comment]
I have found how to fix it,Thanks to Google！
**Just use the pip with version 9.0.3**
# The VIP thing is That your PC have many python，your should use the python27-x64，which the ida7.0 has

> $ C:\python27-x64\Scripts\pip install --user --upgrade pip==9.0.3
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade
 your Python as Python 2.7 won't be maintained after that date. A future version of pip wil
l drop support for Python 2.7.
Looking in indexes: http://pypi.douban.com/simple/
Collecting pip==9.0.3
  Downloading http://pypi.doubanio.com/packages/ac/95/a05b56bb975efa78d3557efa36acaf9cf5d2f
d0ee0062060493687432e03/pip-9.0.3-py2.py3-none-any.whl (1.4MB)
    100% |████████████████████████████████| 1.4MB 423kB/s
Installing collected packages: pip
Successfully installed pip-9.0.3
-----------------------
### After that just use the script to install,BinCat will be installed properly.

**Comment by perfectswpuboy1** [comment]
![ida64_VjAj9taSF6](https://user-images.githubusercontent.com/356742/54683575-ebf7e400-4b4c-11e9-9f38-54b8e4a287ee.png)
